# -*- coding: utf-8 -*-
"""regenerate_instagram_image_urls.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sI_-WW-qOQLIADA3doKeTYDO_A0LtRpG

# Get temp instagram urls.

Most instagram posts have more than one image associated with it. THis script will duplicate the original post row for each image in the post. (You will leave with a longer excel sheet than you started with)


This should take about 30 minutes per 1000 instance. You are free to decrease the sleep range in random.choice - I really have no clue if instagram would boot you for accessing posts faster than the speed of light.

If you don't want to have to keep regenerating the link, use `wget` to download images for longterm storage
"""

!pip install wget

import re
import json

import pandas as pd
import time
from json import JSONDecodeError
import random
import requests

import wget

import urllib.request
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

def import_data_from_drive(share_link, your_name_for_file="my_data"):
  """Brings data file from a google drive sharepoint to your colab workspace.
     It does not require you to host the dataset on your own account.

     Parameters:
     share_link: the link to view a file in google drive
     our_name_for_file: a string describing the file, preferable endling in a file type, ex. 'data.csv'
     """
  id = share_link.split("/")[5] # separate the id from the link
  print("Using id", id, "to find file on drive")

  # use pydrive and colab modules to authenticate you
  auth.authenticate_user()
  gauth = GoogleAuth()
  gauth.credentials = GoogleCredentials.get_application_default()
  drive = GoogleDrive(gauth)
  print("Authenticated colab user")

  # This step will move the file from Drive to the workspace
  download_object = drive.CreateFile({'id':id})
  download_object.GetContentFile(your_name_for_file)
  print("Added file to workspace with name", your_name_for_file)

  return

# YOU CHANGE HERE

link = "https://docs.google.com/spreadsheets/d/12piHij4GRIi8L14IFF57p7RWtOkthC39/edit?usp=sharing&ouid=101042095541764641159&rtpof=true&sd=true"

import_data_from_drive(link, your_name_for_file="influencers.xlsx")

df = pd.read_excel("influencers.xlsx")

df.columns

def get_instance(ob, x):
    url = re.sub(r"\\/", "/", ob['url'])
    instance = x.copy().to_frame().T
    instance['temporary_urls'] = url
    # print(x)
    # print(instance.head())
    return instance
    # urls_to_post_images.append(url)


def handle_unknown_error(url, e):
  print("something went wrong on url", url )
  print("error:", e)
  error_urls.append((url, e))
  return

error_urls = []
subset = df.loc[df['Subtype'] == 'photo']## excluding non-image posts
rows = pd.DataFrame(columns=subset.columns)

# note - its not a good habit to iterate over a dataframe like this. its slow. But in this case we don't mind slow,
# because there is a chance instagram will rate-limit us.
for i, x in subset.iterrows():
  print()
  post_url = x['Url']
  print(post_url)
  urls_to_post_images = []
  # url = "https://www.instagram.com/p/Cm1fufQL0zR/"

  try:

    payload = requests.get(post_url)

    #some json nonsense. pls ignore. If this is breaking its likely that the payload has changed.
    l = re.findall('"image":(\[\{[^\]]*)', str(payload.content))[0]
    l += "]"
    links = json.loads(l)


    print(f"post returned {len(links)} images")
    for ob in links:
      row = get_instance(ob, x)
      rows = pd.concat([rows, row], axis=0)

  except JSONDecodeError:
    try:
      print("JSON DECODE ERROR, removing caption to hopefully get rid of any wierd symbols")
      l = re.sub('caption":.*","representativeOfPage' , 'representativeOfPage', l)
      print(l)
      links = json.loads(l)
      print(f"post returned {len(links)} images")

      for ob in links:
        row = get_instance(ob, x)
        rows = pd.concat([rows, row], axis=0)
    except Exception as e:
      handle_unknown_error(post_url, e)
  except Exception as e:
    handle_unknown_error(post_url, e)
  # break
  time.sleep(random.choice([1,1.5,2])) # I'm such a sneaky hacker

rows.drop(columns=['Unnamed: 0']).reset_index(inplace=True)
rows

# most of the error list is dead posts but saving them just in case you want to investigate
import pickle

with open("error_list", 'wb') as f:
    pickle.dump(error_urls, f)

# probably don't investigate if you are not comfortable working with pickle, list of tuples, etc.

def app(url):
  return url.strip(']\'[').split(', ')

rows["temporary_urls"] = rows["temporary_urls"].apply(app)

# each row should only have one now...

rows['temporary_urls']

rows.to_excel("instagram_images_with_live_links_MAY10.xlsx")

!mkdir /content/image_folder
# !rm  /content/image_folder/*

# Option to store long-term (still need to download from colab)

#acould lso just run this in a local pyton environment.


for i, media_file in enumerate(rows['temporary_urls']):
  wget.download(media_file[0], out =f"/content/image_folder/image{i}.png")

!zip -r /content/image_folder.zip /content/image_folder/

#NOW GO DOWNLOAD THE IMAGE FOLDER.zip

